### ISSUE TITLE
Potential race condition/panic during example/client re-connect scenario

### ISSUE THREAD

**Issue by rgopalakr** [fiorix/go-diameter#101]
1. example/client.go is used for testing "re-connect" to the example/server.go. Please let me know if there are any gaps in my understanding, or if this testing scenario is considered valid or not.
2. client.go is modified(attached client2.go). Client repeatedly attempts "re-connect" to the server whenever  connection is closed by server. Client sends HMR request to server after each successful connection.

	// Makes a persisent connection with back-off.
	log.Println("Use wireshark to see the messages, or try -hello")
	backoff := 1
	for {
		c, err := connect()
		if err != nil {
			log.Println(err)
			backoff *= 2
			if backoff > 20 {
				backoff = 20
			}
			time.Sleep(time.Duration(backoff) * time.Second)
			continue
		}
		log.Println("Client connected, handshake ok")
		backoff = 1
		log.Println("Client sending HMR")
		sendHMR(c, cfg)
		<-c.(diam.CloseNotifier).CloseNotify()
		log.Println("Client disconnected")

		log.Println("Reconnect started")
	}
3. server.go is modified(attached server2.go) to accept maximum of 2 connections. Whenever a third client attempts connection, an "older" client connection is "closed", leaving only a maximum of 2 clients connected.

func (srv *MyServer) HandleConn(peers <-chan diam.Conn) {
    for c := range peers {
        meta, _ := smpeer.FromContext(c.Context())
        addr := c.RemoteAddr().String()
        log.Printf("Peer connected: %s (host=%q realm=%q)",
            addr, meta.OriginHost, meta.OriginRealm)
        srv.mu.Lock()
        srv.peers[addr] = c // store in peers table
        srv.mu.Unlock()
        l := len(srv.peers)
        // max 2 clients connect to the server
	    if l > 2 {
	    	for k := range srv.peers {
	    		if c != srv.peers[k] {
	    			log.Printf("Closing Peer: %s",k)
		    		srv.peers[k].Close()
		    		srv.mu.Lock()
		    		delete(srv.peers, k)
		    		srv.mu.Unlock()
		    		break
	    		}
	    	}
	    }
        go func(c diam.Conn, addr string, meta *smpeer.Metadata) {
            // wait for disconnect notification
            <-c.(diam.CloseNotifier).CloseNotify()
            log.Printf("Peer disconnected %s (host=%q realm=%q)",
                addr, meta.OriginHost, meta.OriginRealm)
            srv.mu.Lock()
            delete(srv.peers, addr) // remove from peers table
            srv.mu.Unlock()
        }(c, addr, meta)
    }

4. Testing done as follows:

$ go run server2.go
2018/12/02 19:22:32 Starting diameter server on :3868
2018/12/02 19:22:42 Peer connected: [::1]:54242 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:42 Received HMR from [::1]:54242:
2018/12/02 19:22:42 Sent HMA to [::1]:54242:

2018/12/02 19:22:49 Peer connected: [::1]:54332 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:49 Received HMR from [::1]:54332:
2018/12/02 19:22:49 Sent HMA to [::1]:54332:

2018/12/02 19:22:56 Peer connected: [::1]:54414 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:56 Closing Peer: [::1]:54242
2018/12/02 19:22:56 Peer disconnected [::1]:54242 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:56 diameter error on [::1]:54242: read tcp [::1]:3868->[::1]:54242: use of closed network connection
2018/12/02 19:22:56 Peer connected: [::1]:54416 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:56 Closing Peer: [::1]:54332
2018/12/02 19:22:56 Peer disconnected [::1]:54332 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:56 diameter error on [::1]:54332: read tcp [::1]:3868->[::1]:54332: use of closed network connection
2018/12/02 19:22:56 Received HMR from [::1]:54414:
2018/12/02 19:22:56 Sent HMA to [::1]:54414:
2018/12/02 19:22:56 Peer connected: [::1]:54418 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")
2018/12/02 19:22:56 Closing Peer: [::1]:54416
2018/12/02 19:22:56 diameter error on [::1]:54416: read tcp [::1]:3868->[::1]:54416: use of closed network connection
2018/12/02 19:22:56 Received HMR from [::1]:54418:
2018/12/02 19:22:56 Sent HMA to [::1]:54418:
2018/12/02 19:22:56 Peer disconnected [::1]:54418 (host="DiameterIdentity{client},Padding:2" realm="DiameterIdentity{go-diameter},Padding:1")

$ go run client2.go
2018/12/02 19:22:42 Use wireshark to see the messages, or try -hello
2018/12/02 19:22:42 Client connected, handshake ok
2018/12/02 19:22:42 Client sending HMR
2018/12/02 19:22:42 Sending HMR to [::1]:3868
2018/12/02 19:22:42 Received HMA from [::1]:3868
2018/12/02 19:22:56 Client disconnected
2018/12/02 19:22:56 Reconnect started
2018/12/02 19:22:56 Client connected, handshake ok
2018/12/02 19:22:56 Client sending HMR
2018/12/02 19:22:56 Sending HMR to [::1]:3868
[no HMA received after re-connect, no DWR/DWA seen in wireshark for this client]

$ go run client2.go
2018/12/02 19:22:49 Use wireshark to see the messages, or try -hello
2018/12/02 19:22:49 Client connected, handshake ok
2018/12/02 19:22:49 Client sending HMR
2018/12/02 19:22:49 Sending HMR to [::1]:3868
2018/12/02 19:22:49 Received HMA from [::1]:3868
2018/12/02 19:22:56 Client disconnected
2018/12/02 19:22:56 Reconnect started
2018/12/02 19:22:56 Client connected, handshake ok
2018/12/02 19:22:56 Client sending HMR
2018/12/02 19:22:56 Sending HMR to [::1]:3868
2018/12/02 19:22:56 Received HMA from [::1]:3868
2018/12/02 19:22:56 diam: panic serving [::1]:3868: close of closed channel
goroutine 24 [running]:
pd.telekom.de/vendor/github.com/fiorix/go-diameter/diam.(*conn).serve.func1(0xc4200beaf0)
	/home/gopalakr/tesa1/tesa/go/src/pd.telekom.de/vendor/github.com/fiorix/go-diameter/diam/server.go:160 +0xd6
panic(0x601ec0, 0x69e320)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
[panic in client, no DWR/DWA seen in wireshark for this client]

$ go run client2.go
2018/12/02 19:22:56 Use wireshark to see the messages, or try -hello
2018/12/02 19:22:56 Client connected, handshake ok
2018/12/02 19:22:56 Client sending HMR
2018/12/02 19:22:56 Sending HMR to [::1]:3868
2018/12/02 19:22:56 Received HMA from [::1]:3868
[ periodic DWR/DWA seen in wireshark for this client]

Expected behaviour: Atleast 2 clients successfully connected to server and periodic DWR/DWA is exchanged
.
Actual behaviour: Only 1 client is connected to server and periodic DWR/DWA is exchanged. Panic/race-condition seen in other 2 clients

[files.tar.gz](https://github.com/fiorix/go-diameter/files/2637013/files.tar.gz)

**Comment by fiorix** [comment]
Looking at this output I cannot tell for sure where the panic is happening, other than it is in one of the handlers.

**Comment by rgopalakr** [comment]
panic serving [::1]:3868: close of closed channel

is attempting to close an already closed channel? ( though client2.go does not do this, i suspect somehow ClientNotify channel is being closed multiple times? )

**Comment by fiorix** [comment]
Could be, although from this particular logging there's no strong evidence. That said, there's been recent changes (as part of SCTP/MultiStreamConn) that could've introduced bugs.

Related code is closeNotify (https://github.com/fiorix/go-diameter/blob/master/diam/server.go#L95) and notifyClientGone (https://github.com/fiorix/go-diameter/blob/master/diam/server.go#L131).

You can fiddle with those two to troubleshoot this problem. I'll be happy to review PRs for this.

**Comment by rgopalakr** [comment]
Based on the logs posted above, i have captured the race-condition in a  sequence diagram below:
eg: in client 2, (go routine 10), there is possibility that "CloseNotify" and "HMA", arrive at the same time, due to which the panic mentioned above was seen. 

![race-condition-analysis](https://user-images.githubusercontent.com/45200138/50398691-94411b00-079f-11e9-99da-edbe709e89cb.png)


I am not clear about the pipeCopyF(), below:
wherein an application response, HMA,(when io.Copy returns nil) is sending 'notifyCilentGone()

`

                 c.sr.pipeCopyF = func() {

                        _, err := io.Copy(pw, readSource)
                        if err == nil {
                                 err = io.EOF
                        }
                        pw.CloseWithError(err)
                        c.notifyClientGone()
                }
`
i modified the pipeCopyF() as below:

`

               c.sr.pipeCopyF = func() {
                        _, err := io.Copy(pw, readSource)
                        if err == io.ErrUnexpectedEOF {
                                err = io.EOF
                                pw.CloseWithError(err)
                                c.notifyClientGone()
                        }
                }
`
which fixed the race condition. attaching complete wireshark trace with the fix.


[wireshark-trace-withfix.tar.gz](https://github.com/fiorix/go-diameter/files/2707154/wireshark-trace-withfix.tar.gz)

**Comment by rgopalakr** [comment]
"If sendHMR is called in a loop, handleHMA should not close 'done'"

Though sendHMR is called in a loop, only one HMR is sent per new connection, server will respond with only one HMA per connection, and i thought it was ok to close 'done' channel.

**Comment by rgopalakr** [comment]
"CloseNotify will only work on a new Read iteration, so - if the server immediately closes a new client connection, client may never get close event"

As per server2.go implementation, server closes the client connection, after handshake, (so the CEA should be on flight). Shouldn't the client's Read iteration have got CEA, before 'CloseNotify' in such a case? Thanks for your valuable inputs...

**Comment by fiorix** [comment]
This has been stuck for too long. Happy to review follow up PRs.
