### ISSUE TITLE
Hardcoded Result-Code in Mesage Answer

### ISSUE THREAD

**Issue by TeoV** [fiorix/go-diameter#102]
Hi,

Thank you for this wonderful library. I would like to ask your opinion regarding an issue we have discovered. According to RFC ( https://tools.ietf.org/html/rfc4006#section-3.2 ), the Result-Code should be after Session-Id, however, this is not really possible when using Answer method. What is the approach you are suggesting, our own Answer method or sending you maybe a patch with some fix (ie: on EmptyResult code, don't add it to the answer)? Many thanks in advance!

Thanks,
TeoV

**Comment by fiorix** [comment]
What you mean by not possible? Each Message has an array of AVP, which allows to set the ordering. Maybe I'm missing something.

**Comment by TeoV** [comment]
Hi Fiorix,

The ResultCode is hardcoded as the first AVP in the answer.
Please see below.
https://github.com/fiorix/go-diameter/blob/master/diam/message.go#L493

Thanks,
TeoV

**Comment by fiorix** [comment]
Fair, but since m.AVP is exported, and is a slice, you could swap the AVPs before writing to the wire. If this is about being compliant to RFC, I wouldn't mind 1) having an extra method that reshuffles AVPs accordingly, or 2) updating the Write* methods to update this slice before writing to the wire.

**Comment by TeoV** [comment]
Hi Fiorix,

How about optional result code in Answer?, ie: 
`if resultCode != 0 {nm.NewAVP(avp.ResultCode, avp.Mbit, 0, datatype.Unsigned32(resultCode))}`
Or if we need resultCode 0, make it pointer in the function signature and check against nil ? 
In this way we would not need to re-order and we can add it later in the method.
I can do a PR if you decide about the way you want to have it.

Thanks,
TeoV

**Comment by fiorix** [comment]
Stuck for too long. Happy to review any PRs as follow up, closing for now.
