### ISSUE TITLE
use pure golang sctp

### ISSUE THREAD

**Issue by ghost** [fiorix/go-diameter#104]
https://github.com/pions/sctp
works for me doing various webrtc things, and so should be stable.
the devs at pions are super responsive too :)

Also a pure golang of DTLS is also in the repo. 
I am not sure how complet it is though. Its enough for webrtc though.

Let me know what you think because go-diameter looks super useful, but i need portability and easy of fixing stuff. Thanks for putting this project up

**Comment by fiorix** [comment]
I think @emakeev would be interested in this. From my end, I wouldn't mind supporting it behind a flag of some kind and letting folks try out in prod, if they can.

**Comment by fiorix** [comment]
Happy to review any PRs on this as follow up.
