### ISSUE TITLE
Incorrect Vendor-ID (10415) for AVP 334, 486, 493 in S6A dictionary

### ISSUE THREAD

**Issue by rdcloyi** [fiorix/go-diameter#105]
The AVP 334, 486 and 493 are used by 3GPP S6A but actually defined in RFC 4004，5447 and 5778. So Vendor-ID of them should be zero instead of 10415. According to this link [https://www.developingsolutions.com/DiaDict/Dictionary/Service-Selection.html](url), it clearly defines vendor ID 0 for AVP 493. Not sure if you agree to update the dictionary.

**Comment by fiorix** [comment]
I wonder what most vendors do, and what would break if we update the dictionary.

**Comment by rdcloyi** [comment]
I am working for Ericsson. At least in my context, it uses vendor ID 0. I had to change it locally to pass my test. For other vendors, I don't know.

**Comment by fiorix** [comment]
If you send a PR we'll review. Can't think of any other action here.
