### ISSUE TITLE
Go diameter can not parse Called-Station-Id avp under PS-Information

### ISSUE THREAD

**Issue by farshadkh** [fiorix/go-diameter#106]
**Unknown-30-0 {Code:30,Flags:0x40,Length:20,VendorId:0,Value:Unknown{0x6c7465346d6f62696e6e6574},Padding:0} (Could not find AVP uint32(30) for Vendor: 0),**

The avp exists in default dictionary, but it seems having non-vendor specific attribute under a vender specific one is not working.

        Service-Information {Code:873,Flags:0xc0,Length:424,VendorId:10415,Value:Grouped{
                PS-Information {Code:874,Flags:0xc0,Length:412,VendorId:10415,Value:Grouped{
                        TGPP-Charging-Id {Code:2,Flags:0x80,Length:16,VendorId:10415,Value:OctetString{0x1fc7107e},Padding:0},
                        TGPP-PDP-Type {Code:3,Flags:0x80,Length:16,VendorId:10415,Value:Enumerated{0}},
                        PDP-Address {Code:1227,Flags:0xc0,Length:20,VendorId:10415,Value:Address{x.x.x.x},Padding:2},
                        TGPP-GPRS-Negotiated-Qos-Profile {Code:5,Flags:0x80,Length:36,VendorId:10415,Value:UTF8String{08-7c0900000fa000009c40},Padding:1},
                        SGSN-Address {Code:1228,Flags:0xc0,Length:20,VendorId:10415,Value:Address{x.x.x.x},Padding:2},
                        GGSN-Address {Code:847,Flags:0xc0,Length:20,VendorId:10415,Value:Address{x.x.x.x},Padding:2},
                        TGPP-IMSI-MCC-MNC {Code:8,Flags:0x80,Length:20,VendorId:10415,Value:UTF8String{x},Padding:3},
                        TGPP-GGSN-MCC-MNC {Code:9,Flags:0x80,Length:20,VendorId:10415,Value:UTF8String{x},Padding:3},
                        TGPP-NSAPI {Code:10,Flags:0x80,Length:16,VendorId:10415,Value:OctetString{0x35},Padding:3},
                        **Unknown-30-0 {Code:30,Flags:0x40,Length:20,VendorId:0,Value:Unknown{0x6c7465346d6f62696e6e6574},Padding:0} (Could not find AVP uint32(30) for Vendor: 0),**

**Comment by fiorix** [comment]
Happy to reopen if there's a PR associated. No action for now so closing it.
