### ISSUE TITLE
Signal Handling with GoDiameter

### ISSUE THREAD

**Issue by brucewayneigsc** [fiorix/go-diameter#108]
I am trying to see how Diameter application will behave when any OS signals are sent. Example:- SIGTERM is raised if i wanted to stop the diameter server. Another server is already up & running to manage HA. Query is how to flush out the existing CCR inside the old server. I should allow only outgoing CCA and block imcoming CCR for a brief amount of time before exiting gracefully.

Any thoughts?

**Comment by fiorix** [comment]
go-diameter does not deal with signals in any way... you can, however, handle signals in your program and tell go-diameter what to do when signals land in the process: close connections, notify peers, etc.

there's nothing specific to go-diameter about how signals should be handled
