### ISSUE TITLE
How to write a single S6a application (HSS) that acts as both a client and the server

### ISSUE THREAD

**Issue by emasean** [fiorix/go-diameter#117]
By using the example codes we have successfully tested the MME initialized message (AIR/AIA/ULR/ULA) for instance) and HSS initialized message (CLR/CLA) separately.

But when it comes to integrating with a real MME, the both ends needs to use the same src/destination port of 3868 instead of a random source port (as when we created separate clients for each other with the example code), so my question is how do we reuse the same diameter server connection when we want to act as a client.

Lets assume our real work scenario, the MME is provided by a 3rd party, it initializes Diameter connection to our diameter server (acting as HSS), then the MME is expecting HSS-initialized traffic (CLR) on the same connection (port 3868 on both ends), how do we reuse the server connection when we send client traffic?

**Comment by emasean** [comment]
So this is how I implemented it for now (not pretty but works):

When doing `handleAIR() or handleULR()` then I can access to the server side `diam.Conn`, I then can use it to issue client request towards the diameter peer (MME).

This only works when AIR or ULR has been received previously, according to diameter protocol CER/CEA are the first messages exchanged so optimally I would like to access the `diam.Conn` already then, but handleCER() is build-in to the go-diameter library so not easy to extract.

**Comment by fiorix** [comment]
> but handleCER() is build-in to the go-diameter library so not easy to extract.

This is only true if you're using the 'sm' package that provide facilities for handshake and session control. Can always copy that code...

**Comment by Jandbacker** [comment]
The 'sm' package has a rather elegant solution to this problem:

type HandshakeNotifier interface {
	// HandshakeNotify returns a channel that receives
	// a peer's diam.Conn after it passes the handshake.
	HandshakeNotify() <-chan diam.Conn
}

With this you can receive diam.Conn (and extract connection and meta data from it) right after a success CER was send to the client .

**Comment by emasean** [comment]
Yes works fine with `HandshakeNotify() <-chan diam.Conn`, put this code in a goroutine just before `listen()` to get the `diam.Conn` from the CER/CEA to be used afterwards.

**Comment by fiorix** [comment]
About using the same port for client and server: you could try using https://godoc.org/github.com/fiorix/go-diameter/diam#DialNetworkBind to bind the local port before dialing out.

**Comment by emasean** [comment]
`DialNetworkBind` may not apply to my case (not the node initializing the diameter connection first)

**Comment by fiorix** [comment]
If you're not dialing out, with the `diam.Conn` from the server's handshake, you can initiate "client" operations. What's missing here?

**Comment by emasean** [comment]
Nothing, all good.
