### ISSUE TITLE
Payload Protocol Identifier in the SCTP layer is set to 00 (meaning 'not specified') and not 2E (meaning 'Diameter')

### ISSUE THREAD

**Issue by edkowalski** [fiorix/go-diameter#119]
Wireshark does not interpret messages sent using those scripts as Diameter ones because the Payload Protocol Identifier in the SCTP layer is set to 00 (meaning 'not specified') and not 2E (meaning 'Diameter').
Is there a way to work around this?

**Comment by fiorix** [comment]
Should be fine now. Closing.
