### ISSUE TITLE
Extracting grouped AVP from incoming message

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#14]
In case of grouped/nested AVPs in the incoming message it is not clear how to properly extract values assigned to those AVPs, for example AVPs defined as follows:

    r.NewAVP(avp.SubscriptionID, avp.Mbit, 0, &diam.GroupedAVP{
                        AVP: []*diam.AVP{
                                diam.NewAVP(avp.SubscriptionIDType, avp.Mbit, 0, datatype.Enumerated(0x00)),
                                diam.NewAVP(avp.SubscriptionIDData, avp.Mbit, 0, datatype.UTF8String(msisdn)),
                        },
                })

or

    r.NewAVP(avp.MultipleServicesCreditControl, avp.Mbit, 0, &diam.GroupedAVP{
                        AVP: []*diam.AVP{
                                diam.NewAVP(avp.RequestedServiceUnit, avp.Mbit, 0, &diam.GroupedAVP{
                                        AVP: []*diam.AVP{
                                                diam.NewAVP(avp.CCTime, avp.Mbit, 0, datatype.Unsigned32(120)),
                                        },
                                }),
                        },
                })

FindAVP seems to work only for the first level of nesting. What would be the recommended way of extracting CCTime for the example above?

**Comment by fiorix** [comment]
FindAVP is a low level call that you never have to use. In order to easily decode your messages, you should define them as a struct with tags and use http://godoc.org/github.com/fiorix/go-diameter/diam#Message.Unmarshal. See this CER handler for example: https://github.com/fiorix/go-diameter/blob/master/diam/serve_test.go#L94.

**Comment by fiorix** [comment]
Oh, I had also added an example of this particular use case: https://github.com/fiorix/go-diameter/blob/master/examples/grouped/grouped.go

**Comment by Josue198s** [comment]
Does anyone has a trace of a group AVP?
