### ISSUE TITLE
Extending dictionaries (3GPP TS 32.299)

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#15]
I am trying to extend dictionaries with additional AVPs, in particular some from the 3GPP TS 32.299 (http://www.3gpp.org/DynaReport/32299.htm) specification. A forwarning: I am new to Go and relatively new to Diameter.

Based on the credit contol dictionary extension, I have tried to define additional library to be loaded in https://github.com/fiorix/go-diameter/blob/master/diam/dict/default.go and added xml to https://github.com/fiorix/go-diameter/tree/master/diam/dict/testdata. Unfortunately I wasn't able to compile the package due to following error:

    gocode/src/github.com/fiorix/go-diameter/diam/dict/default.go:19: syntax error: unexpected name, expecting )
    gocode/src/github.com/fiorix/go-diameter/diam/dict/default.go:942: syntax error: unexpected literal 3, expecting name or (

Which are the lines where extension was defined and loaded. I also tried extending autogen.sh in similar fashion with no luck. My first question is therefore: what is the proper way of defining new dictionary?

As a workaround I pushed additional AVP's to existing credit control dictionary and added relevant codes to https://github.com/fiorix/go-diameter/blob/master/diam/avp/codes.go

Which seems to work, client and server can both send and receive new AVP, however respective packages cannot be decoded in wireshark (and wireshark is able to decode these AVP's coming from different application). Extension is defined as follows:

    <avp name="Service-Information" code="873" must="V,M" may="P" must-not="-" may-encrypt="N">
      -Info
      <data type="Grouped">
        <rule avp="IMS-Information" required="false" max="1"/>
        
      </data>
    </avp>

    <avp name="IMS-Information" code="876" must="V,M" may="P" must-not="-" may-encrypt="N">
      
      <data type="Grouped">
        <rule avp="Called-Party-Address" required="false" max="1"/>
      </data>
    </avp>

    <avp name="Called-Party-Address" code="832" must="V,M" may="P" must-not="-" may-encrypt="N">
      
      <data type="UTF8String"/>
    </avp>

From the wireshark capture I see that Vendor Specific flag is not set, though it is defined in the dictionary so I guess this could be the reason. Could you please advise what is wrong with these definition, why vendor specific flag is not being set?

I could push some definitions from 3GPP TS 32.299 to your library (just a selected few I need so far) if you don't mind and advise the proper way to add these AVPs

**Comment by fiorix** [comment]
When you write any application that requires a different dictionary you should not make changes to go-diameter itself. The `dict.Default` object is a convenience dictionary that has the base protocol and charging applications preloaded, but you are not enforced to use them. In your case I would suggest that you start off with your own xml file containing all you need and use `dict.LoadFile` to make it available to the stack. Then, you create your own constants with the AVPs in your dictionary and just use them. All this requires zero changes in the `go-diameter` package and should work just fine. Once you get your stuff working the way you want, you may consider adding them back into `go-diameter` and sending a pull request.

**Comment by fiorix** [comment]
I think it's a great idea to augment the default dictionaries with 32.299 and perhaps other 3GPP specs, but that's not how you should start.
