### ISSUE TITLE
server closes the connection

### ISSUE THREAD

**Issue by drv1234** [fiorix/go-diameter#174]
Hi,
when I start the example server, it starts but closes the connections after CER/CEA (see capture) and prints this:

> [root@sup4301 hss_go]# go run server.go --addr 10.40.154.76:3868 --diam_host "hss.test.tool" --diam_realm "test.tool"
> 2022/12/13 16:40:30 Starting diameter server on 10.40.154.76:3868
> 2022/12/13 16:40:31 diameter error on 10.37.54.79:33117: read tcp 10.40.154.76:3868->10.37.54.79:33117: use of closed network connection
> 2022/12/13 16:40:32 diameter error on 10.37.54.79:35195: read tcp 10.40.154.76:3868->10.37.54.79:35195: use of closed network connection
> 2022/12/13 16:40:33 diameter error on 10.37.54.79:46787: read tcp 10.40.154.76:3868->10.37.54.79:46787: use of closed network connection
> 2022/12/13 16:40:34 diameter error on 10.37.54.79:45677: read tcp 10.40.154.76:3868->10.37.54.79:45677: use of closed network connection

[dia_server.zip](https://github.com/fiorix/go-diameter/files/10220228/dia_server.zip)

Could you help me?
thanks

**Comment by gato-gto** [comment]
Вт, 13 дек. 2022 г. в 21:54, drv1234 ***@***.***>:

**Comment by drv1234** [comment]
I opened an issue on github (https://github.com/fiorix/go-diameter/issues/).

(btw, I also tried to use client.go from the example but it did not start:
>\# command-line-arguments
>.\client.go:83:3: unknown field 'HostIPAddress' in struct literal of type sm.Settings



the incorrect client.go:
 >line83: 		HostIPAddress:    datatype.Address(net.ParseIP("127.0.0.1")),
 >
the corrected client.go:
 >line83: 		HostIPAddresses:   []datatype.Address{datatype.Address(net.ParseIP("127.0.0.1"))},
 > 		
 
 		

With the corrected example/client.go the connection to example/server.go is not closed. Interesting...

**Comment by drv1234** [comment]
I followed the code down till the ...\Go\src\bufio\bufio.go and there is the source of the error but I don't understand.
I tried the ssh remote port forwarding from the dev server to my local machine the diameter traffic. The server.go was running on my PC and the result is the same. I am confused.
