### ISSUE TITLE
Diameter Client receving CCA

### ISSUE THREAD

**Issue by helioaymoto** [fiorix/go-diameter#184]
Hi,
Trying to get a Diameter Client - Credit-Control, where I have been able to send the CCR Initial based on example code client.go, but even registering the mux to handle CCA:
	mux.Handle("CCA", handleCCA(done))
 I am getting the error:
Could not find preloaded Command with code 272
From what I understood, in v4 the Credit-Control dicitionay is part of the default dictionary and i have read the same in some comments like:
	// Load our custom dictionary on top of the default one, which
	// always have the Base Protocol (RFC6733) and Credit Control
	// Application (RFC4006).

Is it possible to get some support?

**Comment by fiorix** [comment]
The error indicates that the dictionary has not been loaded. Your code is likely missing the call to load the dictionary - default or custom.

**Comment by helioaymoto** [comment]
Hi Fiorix.

Sorry, based on the examples I thought the Default dictionaly is loaded by default...
I tried to load the Credit-Control dictionary like this:

err := dict.Default.Load(bytes.NewReader([]byte(creditcontrolXML)))

Where the creditcontrolXML I have put as a local variable, but i am getting the error as:

2023/11/17 10:44:44 Command: Credit-Control (CC) CODE: 272 cannot be added: index exists

So seems the the 272 (Credit-Control) is already in the Default Dict... so It's not clear to me on how to load the default dictionary only.

**Comment by helioaymoto** [comment]
Thanks Fiorix.
I found the issue in my code... In fact, the dicionary has been loaded correctally, but I was not setting the application-id correctelly when bulding the CCR... Once I fix the application-id (4) it started to work as expected.

m := diam.NewRequest(diam.CreditControl, 4, c.Dictionary())

**Comment by fiorix** [comment]
Perfect!
