### ISSUE TITLE
It seems that it lacks of peer management and routing?

### ISSUE THREAD

**Issue by kingluo** [fiorix/go-diameter#22]
According to the RFC 6733, at least below features are missing in this implementation?
* connection election between peers
* peer tables and management
* routing table and message routing

I think the practical diameter application should need these features.

**Comment by fiorix** [comment]
Right, and I'm not sure how those would fit as a framework. All items you mentioned are specific to how you build your application: e.g. when handling DPR, handle election. Peer table is something you populate upon CER and use whenever applicable, same as routing.

I'm open to suggestions, but don't really think these things belong to a framework.

**Comment by kingluo** [comment]
Thanks for your reply.
Well, I also think the handler mechanism could be used to supply those high level stuff, but one question, where to place the peer tables? I think the server structure should reserve some room for those global data (maybe some data are even connection related).
And I think the document should clarify that which content of RFC are implemented and which are not, then it should be more user-friendly (I read over the codes and then found which are missing).

**Comment by kingluo** [comment]
One more question, does the framework consider the AVP mandatory bit and be agent extensible?
* if the mandatory bit is unset, then the receiver should ignore the parse error, e.g. if it could not find the corresponding dictionary
* for relay/redirect agent, it doesn't matter if the agent could not understand some AVPs in the command

**Comment by fiorix** [comment]
You're right about the handler reserving room for peer tables and other stuff, but it's totally up to how you design your software.

Each handler provides you with a `diam.Conn` object that represents a peer, so if you get that in a CER it means the peer has just connected and is attempting a handshake. If you use the state machine from `diam/sm`, it handles CER for you and sends new peer's `diam.Conn` over a channel once they're acknowledged the CER.

You can easily create a mechanism to populate and cleanup the peers table. See the example below, which uses the state machine:

	package main
	
	import (
		"log"
		"sync"
	
		"github.com/fiorix/go-diameter/diam"
		"github.com/fiorix/go-diameter/diam/avp"
		"github.com/fiorix/go-diameter/diam/datatype"
		"github.com/fiorix/go-diameter/diam/sm"
		"github.com/fiorix/go-diameter/diam/sm/smpeer"
	)
	
	type Server struct {
		mu    sync.Mutex
		peers map[string]diam.Conn // peer index by ip:port
	}
	
	func main() {
		srv := &Server{
			peers: make(map[string]diam.Conn),
		}
		mux := sm.New(&sm.Settings{
			OriginHost:       "foobar",
			OriginRealm:      "test",
			VendorID:         13,
			ProductName:      "go-diameter",
			FirmwareRevision: 1,
		})
		go srv.HandleConn(mux.HandshakeNotify())
		mux.HandleFunc("ACR", srv.HandleACR)
		err := diam.ListenAndServe(":3868", mux, nil)
		if err != nil {
			log.Fatal(err)
		}
	}
	
	func (srv *Server) HandleConn(peers <-chan diam.Conn) {
		for c := range peers {
			meta, _ := smpeer.FromContext(c.Context())
			addr := c.RemoteAddr().String()
			log.Printf("Peer connected: %s (host=%q realm=%q",
				addr, meta.OriginHost, meta.OriginRealm)
			srv.mu.Lock()
			srv.peers[addr] = c // store in peers table
			srv.mu.Unlock()
			go func(c diam.Conn, addr string, meta *smpeer.Metadata) {
				// wait for disconnect notification
				<-c.(diam.CloseNotifier).CloseNotify()
				log.Printf("Peer disconnected %s (host=%q realm=%q)",
					addr, meta.OriginHost, meta.OriginRealm)
				srv.mu.Lock()
				delete(srv.peers, addr) // remove from peers table
				srv.mu.Unlock()
			}(c, addr, meta)
		}
	}
	
	func (srv *Server) HandleACR(c diam.Conn, m *diam.Message) {
		// iterate over all AVPs in this message, it's an array:
		for _, avp := range m.AVP {
			log.Println(avp)
		}
		// or, optionally map the AVPs of your interest into your
		// own data structure...
		type myAVP struct {
			HostAVP  *diam.AVP           `avp:"Origin-Host"`            // map the AVP object as-is
			HostData string              `avp:"Origin-Host"`            // map just the AVP data to a string
			artAVP   *diam.AVP           `avp:"Accounting-Record-Type"` // map the AVP object as-is
			artData1 datatype.Unsigned32 `avp:"Accounting-Record-Type"` // just the data as diam.Unsigned32
			artData2 uint32              `avp:"Accounting-Record-Type"` // just the data as native uint32
		}
		var d myAVP
		err := m.Unmarshal(&d)
		if err != nil {
			return // respond with something before returning
		}
		// create the answer object
		a := m.Answer(diam.Success)
		// create new AVPs for the answer
		a.NewAVP(avp.OriginHost, avp.Mbit, 0, datatype.DiameterIdentity("foobar"))
		// or add existing AVPs to the answer
		a.AddAVP(d.HostAVP) // not this Origin-Host, this is just an example
		// respond to this peer by writing to c, or pick another
		// peer from srv.peers
		a.WriteTo(c)
	}

This is obviously not handling the Accounting-Request in a proper way, it's just to show you that it's up to you to parse AVPs, handle the mandatory bit and so on.

**Comment by fiorix** [comment]
Also, every `diam.Conn` object provides you with a `Context` object from https://godoc.org/golang.org/x/net/context, so you can actually store things in that object for later use in other handlers.

**Comment by nsmosi** [comment]
> According to the RFC 6733, at least below features are missing in this implementation?
> 
> * connection election between peers
> * peer tables and management
> * routing table and message routing
> 
> I think the practical diameter application should need these features.

Actually the features that you mentioned it is for DRA (Diameter Routing Agent) it is different component, which I don't believe the diam lib should deal with, it is different functionality, the diam lib should care about the core diameter functionality only, you can still use the lib and develop your own DRA, I have already developed one and currently testing it.
so the DRA will do:
> * connection election between peers
> * peer tables and management
> * routing table and message routing
