### ISSUE TITLE
Problem having vendor specific AVP with an existing AVP code

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#23]
According to RFC:
"The AVP Code, combined with the Vendor-Id field, identifies the  attribute uniquely."

But currently I seem to have some parsing problems if you use a vendor specific AVP with a code that already exists. At least in avp/codes.go this looks a bit odd:

dictAVP, err := dictionary.FindAVP(application, a.Code)

Because the FindAVP doesn't take vendorId as parameter.

**Comment by jaroszan** [comment]
Can you please provide the specific example that doesn't work?

For me the advice from https://github.com/fiorix/go-diameter/issues/14 worked fine with vendor specific AVPs.

**Comment by taseppa** [comment]
Here is a simple testcase, when printing the message it says "myavp2" but should say "myavp"

```golang
package main

import (
	"bytes"
	"log"

	"github.com/fiorix/go-diameter/diam"
	"github.com/fiorix/go-diameter/diam/avp"
	"github.com/fiorix/go-diameter/diam/datatype"
	"github.com/fiorix/go-diameter/diam/dict"
)

func main() {
	err := dict.Default.Load(bytes.NewReader(customApp))

	if err != nil {
		log.Fatal(err)
	}

	err = dict.Default.Load(bytes.NewReader(customApp2))
	if err != nil {
		log.Fatal(err)
	}

	m := diam.NewMessage(1111, diam.RequestFlag, 999, 1, 2, dict.Default)
	m.NewAVP(2, avp.Mbit, 0, datatype.OctetString("foobar"))


	log.Printf("m:\n%s\n", m)
}

var customApp = []byte(`<?xml version="1.0" encoding="UTF-8"?>
<diameter>
	<application id="999">

                <avp name="myavp" code="2" must="-" may="P" must-not="M" may-encrypt="Y">
                        <data type="OctetString"/>
                </avp>


		<command code="1111" short="TC" name="Test-Command">
			<request>
				<rule avp="myavp" required="true" max="1"/>
			</request>

		</command>
	</application>
</diameter>
`)



var customApp2 = []byte(`<?xml version="1.0" encoding="UTF-8"?>
<diameter>
	<application id="999">
                <vendor id="11111" name="customvendor"/>
                <avp name="myavp2" code="2" must="V" may="P" must-not="M" may-encrypt="Y">
                        <data type="OctetString"/>
                </avp>


		<command code="1111" short="TC" name="Test-Command">
			<request>
				<rule avp="myavp2" required="true" max="1"/>
			</request>
		</command>
	</application>
</diameter>
`)
```

**Comment by jaroszan** [comment]
I am sure what was the idea behind the original design but it seems there is a workaround:

    const customAppTest = "mybase.xml"
    ...
    myDict, err := dict.NewParser(customAppTest)
    ... 
    m := diam.NewMessage(1111, diam.RequestFlag, 999, 1, 2, myDict)

**Comment by fiorix** [comment]
In your original program you're not setting the vendor ID in NewAVP: https://godoc.org/github.com/fiorix/go-diameter/diam#NewAVP

So if you do `m.NewAVP(2, avp.Mbit, 99, datatype.OctetString("foobar"))` you should get 99 as the vendor. The underlaying API won't ever try to normalize that based on the dictionary.

**Comment by jaroszan** [comment]
I guess the idea behind the example was that vendor specific avp overlaps with base dictionaries (id=0).

**Comment by taseppa** [comment]
The point of the example is that I do NOT set the vendor ID. So in this case when parsing the message myavp should be returned NOT myavp2.

In your workaround do you mean that the two dictionaries are combined into one separate file? Anyways if that works it's just a workaround, not a proper solution.

**Comment by jaroszan** [comment]
In the workaround you are creating separate dictionary if you have duplicates. I have tested in by modifying your example, but I don't know what use case you are basing it on (still I see your point in this very simplified example)

If you can supply the whole test case it would be possible to say what can work in your particular case. Do you have some real life example when IANA AVP codes overlap with codes in vendor specific namespace?

**Comment by taseppa** [comment]
Well we have our own vendor specific AVPs and these overlap with the base protocol AVPs. Because this is allowed by RFC, there seems to be an obvious bug when parsing the AVPs.

**Comment by jaroszan** [comment]
For your particular case does the decoded network trace look as expected?

It looks that both vendor ID and avp code are set correctly, but the problem occurs during logging name to terminal. Since AVP header contains Code and Vendor ID that should not be the problem.

**Comment by taseppa** [comment]
Yeah the decoded network trace looks normal. The problem is with parsing of the message.

**Comment by fiorix** [comment]
The parsing code does not take vendor id into consideration, that's probably why. Should be an easy fix, I can go back to this later on and update this ticket. For reference, I believe this is the function that needs change: https://github.com/fiorix/go-diameter/blob/master/diam/avp.go#L50

**Comment by taseppa** [comment]
Hey, any update on this one?

**Comment by fiorix** [comment]
No but I have a better idea of how to do this. We'll need a `dict.FindAVP` that takes application ID, vendor ID and AVP code. Will do this whenever I find time, or whenever someone sends a PR that I can review.

**Comment by danbogos** [comment]
Hi @fiorix 

We got also bitten from this issue (AVPs are incorrectly  matching between standard and vendor namespace). If you have a clear idea about how you want to do it and no time, I could try to do it myself since it is kinda show stopper for us, just show me the changes you want to be done.

Ta,
DanB

**Comment by fiorix** [comment]
Hey @danbogos it should probably start by the dictionary parser struct `dict.Parser` where AVPs are indexed after we parse the xml dictionary. As you can see here (https://github.com/fiorix/go-diameter/blob/master/diam/dict/parser.go#L33) all AVPs are indexed by name or code, and vendor ID is not there. It should be an extra field in the `codeIdx` struct, and a parameter to `dict.FindAVP` function.

From there, all calls that use the `dict.FindAVP` in the `diam` package should be updated, and this will be a backwards incompatible change although should not affect too many users if they are using the package correctly.

Let me know if you have any further questions and we can keep this ticket alive.

**Comment by danbogos** [comment]
Will check it, thanks! 
Could do a dict.FindAVPWithVendor until your users migrate if you think the backwards incompatibility can influence them. 

DanB

**Comment by fiorix** [comment]
Good point, but then all functions in the `diam` package have to support that semantic.
