### ISSUE TITLE
Does Unmarshal support enums?

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#24]
I tried to unmarshal message containing enum AVPs as int32 values but the value was always 0. The reflect_test.go doesn't contain examples of enum AVP types. Am I just doing something wrong or maybe there is some problem with enum types?

**Comment by fiorix** [comment]
Enum types are essentially Unsigned32, but I don't remember testing them. It's possible that there's a bug, although there shouldn't! :)

I can take a look later and write a proper test with enums.

**Comment by taseppa** [comment]
Hey,

I think it was just user error, I had initially:

```RequestType int    `avp:CC-Request-Type````

Instead of:

```RequestType int    `avp:"CC-Request-Type"````

**Comment by fiorix** [comment]
Yeah that's a fix
