### ISSUE TITLE
Updating AVP values

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#27]
It would be useful to add a method for updating AVP values. Currently I have been using this helper function:

func ReplaceAVPValue(m *diam.Message, avpName string, avpValue datatype.Type) error {

	avp, err := m.FindAVP(avpName)

	if err != nil {
		return err
	}

	oldLength := avp.Len()
	avp.Data = avpValue
	newLength := avp.Len()
	m.Header.MessageLength += uint32(newLength) - uint32(oldLength)

	return nil
}

But I'm not sure if it works for AVPs that are inside grouped AVP.

**Comment by fiorix** [comment]
Still don't understand why you're insisting in doing it the hard way with FindAVP, and to update messages. Why not just do `m.Unmarshal` of exactly what you want and build the next message exactly how you want it?

**Comment by taseppa** [comment]
I'm not sure how Unmarshal would help in this case. In this case I am not making a new message from scratch but modifying an existing message by just changing one AVP value.

**Comment by fiorix** [comment]
The problem of modifying AVPs is that they may exist anywhere in the message, and it gets worse when they can be grouped. Not sure we can put this in the package API.

**Comment by taseppa** [comment]
Okay I can see your concern. Another option is to add a similar method to AVP implementation, the developer will be responsible for finding the correct AVP.

Maybe you are still not quite convinced why such operations are important. Consider a diameter proxy, its main purpose is to route traffic from one place to another leaving the message contents unchanged. The received messages can be very complex. In some cases small modifications to the messages may need to be made. Like changing certain AVP values, adding new AVPS, or deleting existing ones. I don't think the current library has currently very good tools for dealing with such usecase.

**Comment by fiorix** [comment]
If you know the exact spot of the AVP or AVPs you're looking for in a message, you can use `Unmarshal` to get just pointers to those AVPs then modify and reuse in any way you want. I don't really understand what's so limiting. Could you please show an example?

**Comment by taseppa** [comment]
Well let's say we receive a CCR message and we want to replace the Origin-Realm with our own value and leave everything else intact. We can't be sure what other AVPs the CCR message contains. How would you do this? Is there a related Marshal operation in addition to Unmarshal?

**Comment by fiorix** [comment]
Yes, you can definitely use `Unmarshal` to get a pointer to that AVP in your message then update it and re-send the very same message.

**Comment by taseppa** [comment]
Not sure i'm following, lets say i have the following code:

type CCRMessage struct {
	ProductName   string `avp:"Product-Name"`
}

var d Data
if err := m.Unmarshal(&d); err != nil {
	t.Fatal(err)
}

d.ProductName = "foobar"

Is it somehow possible to send a new message now with the modified product name but all other AVPs intact?

**Comment by fiorix** [comment]
You can't unmarshal to a string and expect it to change the original message. That's why I mentioned pointers to the AVPs in the message:

    type CCRMessage struct {
      ProductName *diam.AVP `avp:"Product-Name"`
    }

When you unmarshal, that ProductName *is* the original AVP in the message, and you can change it.

**Comment by taseppa** [comment]
Now that I have the pointer to the AVP, how would I change the contents of the AVP to "foobar"?

**Comment by fiorix** [comment]
You set the `Data` field of the AVP to a valid diameter datatype. Assuming this is an `OctetString` for example, you could do:

    myptr.Data = datatype.OctetString("foobar")

**Comment by taseppa** [comment]
But if I do it like this are the message headers updated accordingly, like for example the message length?

**Comment by fiorix** [comment]
Looking again at `Message.SerializeTo` and `AVP.SerializeTo` it indicates that it should be updated and serialized correctly based on `AVP.Data`. If you find any issues there it should be pretty easy to fix.

**Comment by fiorix** [comment]
Does it make more sense to you now? This way you can capture the pointer of any AVP in the message and update it to your needs then re-send the same message multiple times. Definitely a lot less work than using `FindAVP` manually and the struggles with grouped AVPs.

**Comment by taseppa** [comment]
Hm yes if it works it makes sense. How about adding new AVPs to a grouped AVP?

**Comment by fiorix** [comment]
The `diam.GroupedAVP` type is a struct with an `[]*AVP` slice in it, you can `append` any AVPs to it. See the definition: https://godoc.org/github.com/fiorix/go-diameter/diam#GroupedAVP

And here's an example of manually adding more AVPs: https://github.com/fiorix/go-diameter/blob/master/examples/grouped/grouped.go#L27

**Comment by taseppa** [comment]
I'm not sure removal of AVP values works, or maybe I'm doing something wrong. In client side i try to do:

avps := message.AVP
avps = append(avps[:2], avps[2+1:]...)
message.WriteTo(connection)

But when receiving I get this error:

2015-10-27 09:43:52 ERROR Error:%!(EXTRA *errors.errorString=Failed to decode AVP: Not enough data to decode AVP: 16 != 18)

**Comment by taseppa** [comment]
I think the problem is that SerializeTo relies on the value of the MessageLength and when you directly remove the AVP MessageLength is not updated. So either SerializeTo needs to be modified so that the MessageLength is calculated during serialization or add some kind of RemoveAVP method that updates the message length.

**Comment by fiorix** [comment]
We can easily support this if we re-calculate the message length in `SerializeTo` by adding this:

    m.Header.MessageLength = uint32(m.Len())

As the first line of the `SerializeTo` function, here: https://github.com/fiorix/go-diameter/blob/master/diam/message.go#L258

**Comment by fiorix** [comment]
Looking at this more closely it seems the right place might be `WriteTo` to avoid calling `Len` twice.

**Comment by taseppa** [comment]
On a related note it seems removing AVPs is a bit tricky because just getting the AVP pointer doesn't help much (?). You need to somehow get the index in the AVP array to remove the AVP and i'm not sure what's the best way to do that.

**Comment by fiorix** [comment]
If you have the pointer to it you can scan the AVP slice and compare pointers, then remove it. It'll be tricky with grouped and nested AVPs.

**Comment by taseppa** [comment]
Hey currently I have been using this code for removing AVPs:

```
func (m *Message) removeAVP(avps []*AVP, code interface{}, parentAVP *GroupedAVP) (error) {
	var avpPointer *AVP

	for index, a := range avps {
		if  (reflect.ValueOf(code).Type().AssignableTo(reflect.TypeOf(avpPointer)) && a == code) || a.Code == code {
			if parentAVP != nil {
				parentAVP.AVP = append(parentAVP.AVP[0:index], parentAVP.AVP[index+1:]...)
			} else {
				m.AVP = append(m.AVP[0:index], m.AVP[index + 1:]...)
			}
			m.Header.MessageLength -= uint32(a.Len())
			return nil
		}

		if a.Data.Type() == GroupedAVPType {
			groupedAVP := a.Data.(*GroupedAVP)
			ret := m.removeAVP(groupedAVP.AVP, code, groupedAVP)
			if ret == nil {
				return ret
			}
		}
	}

	return errors.New("AVP not found")
}

func (m *Message) RemoveAVPByPointer(avp *AVP) error {
	return m.removeAVP(m.AVP, avp, nil)
}

func (m *Message) RemoveAVP(code interface{}) error {
	fmt.Printf("Trying to remove AVP %s", code)

	dictAVP, err := m.Dictionary().FindAVP(m.Header.ApplicationID, code)

	if err != nil {
		return err
	}

	return m.removeAVP(m.AVP, dictAVP.Code, nil)
}
```

It works but contains a lot of similarities with findAVP code so it could be refactored a bit. Do you think merging this code, possibly after some refactoring, to go-diameter master branch would be beneficial?

**Comment by fiorix** [comment]
Sure, you can definitely try to harmonize them so long you can unit test all corner cases and ensure it does not crash. Also, avoid using reflection first in your code above, you should switch the test of `a.Code == code` first, then try the reflect test.

The reason for that is that reflection slow things down considerably. For example, if you look at the message parser benchmark without reflection:

    BenchmarkReadMessage-4 	  300000	      5067 ns/op

Versus the parser using `Unmarshal`, which uses reflection:

    BenchmarkUnmarshal-4   	  300000	      5733 ns/op

That adds a 13% overhead to the code.

**Comment by fiorix** [comment]
Can we close this already?

**Comment by taseppa** [comment]
Closing, I will provide pull request for the AVP removal later.
