### ISSUE TITLE
Handling AVPs where the payload is empty

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#29]
Currently if AVP doesn't contain any payload it causes go-diameter to panic when parsing the message. The problem happens in unsigned32.go:17, and likewise for other datatypes. Example case where I encountered this is Failed-AVP containing AVP that has no payload. 

RFC says:

A Diameter message SHOULD contain one Failed-AVP AVP, containing the
   entire AVP that could not be processed successfully.  If the failure
   reason is omission of a required AVP, an AVP with the missing AVP
   code, the missing Vendor-Id, and a zero-filled payload of the minimum
   required length for the omitted AVP will be added. 

So it seems it is recommended to zero fill the payload but it's not mandatory.

**Comment by fiorix** [comment]
Is this an AVP you're getting off the wire or an AVP you're generating?
If it's from the network please provide me with a pcap to take a look. Otherwise you should provide the empty payload, which is an interface and currently cannot be nil. We could definitely talk about adding checks to all data types but that might cost performance.

**Comment by taseppa** [comment]
I'm getting this off wire. I would be happy to provide pcap but the AVPs contain some potentially sensitive information I can' share.

**Comment by fiorix** [comment]
So you're saying the parser crash when a `FailedAVP` is received, containing the failed AVP with empty data? I can't reproduce that.

**Comment by jaroszan** [comment]
@taseppa: may be you can provide which failed AVP you are receiving and code for the parser? Some relevant text extract from pcap without sensitive information?

**Comment by taseppa** [comment]
It should happen with every AVP that is of type unsigned32. If you check unsigned32.go:17

return Unsigned32(binary.BigEndian.Uint32(b)), nil

This will panic if byte array is empty http://play.golang.org/p/6ctpKdZ0H0

**Comment by fiorix** [comment]
This patch should fix it, let me know otherwise.

**Comment by fiorix** [comment]
At some point we might want to do some more strict checks in all these decoder functions to ensure the data is the exact length we want. If zero (the case of embedded in `FailedAVP`) we return default value, if exact length we decode, other than that we return error.

**Comment by taseppa** [comment]
This patch looks good, thanks!
