### ISSUE TITLE
Tool for converting go-diameter dictionaries to wireshark dictionaries?

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#32]
I just noticed there is a tool that converts wireshark dictionaries to go-diameter dictionaries. I guess there is no tool that does the conversion other way? Of course to prevent this problem one could always just create the wireshark dictionary first, but sometimes to realize this it can be already too late :)

**Comment by fiorix** [comment]
That tool isn't finished either.. I started doing it but hit some corner cases and didn't put enough effort to make it work flawless all the time. We can definitely revisit and perhaps even support wireshark dictionaries to make things easier.

**Comment by taseppa** [comment]
Yeah supporting wireshark dictionaries directly doesn't like a bad idea.

**Comment by fiorix** [comment]
This has been hanging here for too long. I'm happy to reopen if someone is interested in working on it.
