### ISSUE TITLE
Failed to decode AVPs with Vendor-Id

### ISSUE THREAD

**Issue by mspronk** [fiorix/go-diameter#39]
When trying to decode a message that has AVPs with vendor-ids, that are in the default.go dictionary, ReadMessage errors out with "`Failed to decode AVP: Could not find AVP XXX`".

Verified by adding a test case in diam/message_test.go for a message with a Service-Information AVP (873). This is defined in default.go, but missing the vendor-id. This seems to be the case for all AVPs defined in the variable `tgpprorfXML`.

Proposed solution is adding `vendor-id="10415"` to each of these AVPs in default.go.
(PS Interim solution that worked for me for now was adding a corrected version of the entire `tgpprorfXML` section to my custom dictionary).

Will create a pull request for this fix.

**Comment by fiorix** [comment]
Well, the Vendor ID is there: https://github.com/fiorix/go-diameter/blob/master/diam/dict/default.go#L1906

Perhaps the dictionary parser is not using that value for all AVPs in that dictionary. I wouldn't want to have it on each AVP. Maybe this is related to the changes from @danbogos?

**Comment by fiorix** [comment]
O well... looking again, the dictionary itself support multiple Vendor IDs, and each AVP can only support one. So I guess the only way to make it proper is by updating each AVP.

**Comment by danbogos** [comment]
@fiorix,

In my implementation the vendorId as general for application was not considered but the vendor_id parameter in the avp definition. Looking in the documents I could find around, that was also proposed in some dictionary formats .... one vendor_id per AVP.

Cheers,
DanB

**Comment by danbogos** [comment]
To talk facts, here is how we define them (and it works now both ways with go-diameter):
https://github.com/cgrates/cgrates/blob/master/data/diameter/dict/huawei/3gpp_vendor.xml#L5

DanB

**Comment by fiorix** [comment]
Thanks Dan, that's the right thing to do. So for #40 the Ro/Rf dictionary is fixed now.

**Comment by danbogos** [comment]
Great, thanks for confirming it since it is all new ground for me also.

DanB

**Comment by jaroszan** [comment]
That's an interesting issue which I didn't encounter during tests. AVPs in my case were defined as follows and were encoded/decoded correctly:

    m.NewAVP(avp.ServiceInformation, avp.Mbit|avp.Vbit, 10415, &diam.GroupedAVP{
		AVP: []*diam.AVP{
			diam.NewAVP(avp.IMSInformation, avp.Mbit|avp.Vbit, 10415, &diam.GroupedAVP{
				AVP: []*diam.AVP{
					diam.NewAVP(avp.CalledPartyAddress, avp.Mbit|avp.Vbit, 10415, datatype.UTF8String(to)),
				},
			}),
		},
	})

**Comment by fiorix** [comment]
Can we close this after the last patches?

**Comment by mspronk** [comment]
Yeah, as far as I can tell it's been resolved.

Thanks,
Martijn
