### ISSUE TITLE
Support Multiple Dictionaries

### ISSUE THREAD

**Issue by dwilkie** [fiorix/go-diameter#4]
`func NewMessage` in `message.go` accepts a dictionary argument as the final argument:

``` go
func NewMessage(cmd uint32, flags uint8, appid, hopbyhop, endtoend uint32, dictionary *dict.Parser) *Message {
```

however some of the AVP's are shared and are used across multiple dictionaries

For example:

``` xml
<!-- dict/testdata/base.xml -->
<avp name="Session-Id" code="263" must="M" may="P" must-not="V" may-encrypt="Y">
  <data type="UTF8String"/>
</avp>
```

``` xml
<!-- dict/testdata/credit_control.xml -->
<command code="272" short="CC" name="Credit-Control">
  <request>
    <rule avp="Session-Id" required="true" max="1"/>
    <rule avp="Origin-Host" required="true" max="1"/>
    <!-- More AVP Rules >
```

I'm not sure what the best approach here is, but maybe we can pass in an array of dictionaries as the final argument to `func NewMessage`?

**Comment by nsmosi** [comment]
Gy Credit Control and Gx Credit-Control are having the same command code (272), so I tried to load Gx Credit control it is complaining about existing code:

`Command: Credit-Control (CC) CODE: 272 cannot be added: index exists`

While they are having different application-Id , don't know what to do ?
