### ISSUE TITLE
Error "missing Origin-State-Id" whilst using diam/sm.

### ISSUE THREAD

**Issue by micrypt** [fiorix/go-diameter#42]
Attempting to use state machine in a similar fashion as the `client.go` example, results in an error, `missing Origin-State-Id`. There's no clear way to update the handshake CER with the AVP in question in the case that it is indeed missing. A snippet from the application is below: 

```
    smcli := &sm.Client{
        Dict:               dict.Default,
        Handler:            mux,
        MaxRetransmits:     3,
        RetransmitInterval: time.Second,
        EnableWatchdog:     true,
        WatchdogInterval:   5 * time.Second,
        AcctApplicationID: []*diam.AVP{diam.NewAVP(avp.AcctApplicationID, avp.Mbit, 0,
            AcctApplicationID),
        },
    }

    // Set message handlers.
    mux.HandleFunc("CCA", cl.ccaHandler)

    // Print error reports.
    go printErrors(mux.ErrorReports())

    connect := func() (diam.Conn, error) {
        c, err := smcli.Dial(serverAddress)
        cl.c = c
        return cl.c, err
    }
```

**Comment by fiorix** [comment]
Sounds like the error you get is because the server you're connecting to does not respond with a CEA containing `Origin-State-Id`. Can you confirm that with a pcap?

**Comment by micrypt** [comment]
@fiorix You're absolutely correct. It's sending back an error message (3099). 

```
   DIAMETER_INVALID_AVP_BITS          3009
      A request was received that included an AVP whose flag bits are
      set to an unrecognized value, or that is inconsistent with the
      AVP's definition.
```

Is there a way to override the CER within the state machine's `handshake()`?

**Comment by micrypt** [comment]
@fiorix Curiously, the only way I've managed to get a valid CEA response thus far has been to completely remove the FirmwareRevision AVP.

https://github.com/fiorix/go-diameter/blob/master/diam/sm/client.go#L179

**Comment by fiorix** [comment]
I see, the `Firmware-Revision` AVP is not mandatory but the state machine will always include it. We have to patch it and make this optional somehow. Not sure how I want this implemented, need to think about it. Can't do for e.g. if revision=0 does not include, but also don't want to add a boolean field to that struct. Ideas are welcome.

**Comment by fiorix** [comment]
Closing this in favor of #44.

**Comment by micrypt** [comment]
@fiorix Would you mind reopening this as it's not quite a fit with #44. It turns out the CEA truly doesn't include the `Origin-State-Id` AVP even when it is present in the CER. It responds with `DIAMETER_SUCCESS` but skips returning a `Origin-State-Id`, at which point the state machine freaks outs. I suspect one ought to avoid throwing an error when it's not present in the answer. BTW, it does the same with the DWR/DWA cycle.

**Comment by fiorix** [comment]
Sure

**Comment by fiorix** [comment]
Could you please try this dev branch?
