### ISSUE TITLE
Package install failure: import cycle error (Go 1.5.3)

### ISSUE THREAD

**Issue by micrypt** [fiorix/go-diameter#43]
Attempting to install the package currently fails with an import cycle error.

```
micrypt@box /usr/local/bin [master] $  echo $GOPATH
/Users/micrypt/silo/gocode
micrypt@box /usr/local/bin [master] $  echo $GOROOT
/Users/micrypt/silo/go
micrypt@box /usr/local/bin [master] $  go get github.com/fiorix/go-diameter/diam
import cycle not allowed
package github.com/fiorix/go-diameter/diam
	imports bufio
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
```

**Comment by fiorix** [comment]
Definitely something wrong on your end and I can't reproduce. Tested on different machines and also different Go versions.

Here's an example using Docker:

    docker run --rm -it golang:1.5.3 sh -c '(go get github.com/fiorix/go-diameter/diam && go test -v github.com/fiorix/go-diameter/diam/...)'

Same works with the `golang:1.6rc1` image and so on...

**Comment by micrypt** [comment]
@fiorix Alright. Thanks for checking.
