### ISSUE TITLE
Make Firmware-Revision AVP optional in State Machine

### ISSUE THREAD

**Issue by fiorix** [fiorix/go-diameter#44]
Package `sm` always include the `Firmware-Revision` AVP in client connections and expect it to exist in server connections during the initial handshake.

This must be optional. See #42 for details.

**Comment by fiorix** [comment]
Please try the dev branch.

**Comment by micrypt** [comment]
@fiorix Changes in dev are pretty much equivalent to the local changes I ended up making to get it working. Works just fine.

**Comment by fiorix** [comment]
Good. Since this patch contains fixes for both #44 and #42, could you confirm it also works for #42?

**Comment by micrypt** [comment]
Yes. Thanks.
