### ISSUE TITLE
Unsupported address family: 0x0008

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#45]
When I receive a message I get an error as in subj.

Ethernet layer in wireshark says:

```
Type: IPv4 (0x0800)
```

IP layer is decoded as:

```
Internet Protocol Version 4, Src: 172.20.21.7, Dst: 172.20.17.37
0100 .... = Version: 4
.... 0101 = Header Length: 20 bytes
Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
Total Length: 580
Identification: 0xa4a1 (42145)
Flags: 0x02 (Don't Fragment)
Fragment offset: 0
Time to live: 62
Protocol: TCP (6)
Header checksum: 0x5a51 [validation disabled]
Source: 172.20.21.7
Destination: 172.20.17.37
[Source GeoIP: Unknown]
[Destination GeoIP: Unknown]
```

**Comment by fiorix** [comment]
That's because we don't support 0x0800:

https://github.com/fiorix/go-diameter/blob/master/diam/datatype/address.go#L17

**Comment by fiorix** [comment]
For reference, the RFC part for this specific data type:

https://tools.ietf.org/html/rfc6733#section-4.3.1

And the list of IANA address families:

http://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml

**Comment by jaroszan** [comment]
Initially I have looked at the wrong place, it seems I have found the AVP which causes the error (http://www.etsi.org/deliver/etsi_ts/132200_132299/132299/12.09.00_60/ts_132299v120900p.pdf#page=157):

> 7.2.170 Recipient-SCCP-Address
> The Recipient-SCCP-Address AVP (AVP code 2010) is of type Address. It is the "SCCP called address" used by the messaging node when delivering the message. This is usually the address of the MSC or SGSN/Serving Node that is serving the UE when it delivers the message. It contains a Global Title, where Global Title represents an E.164 number,  and possibly a Point Code (ISPC). The AddressType discriminator in RFC 3588 [401] is set to value 8, E.164, and the  address information is UTF8 encoded. 

Can you please advise what should be the scope of changes to make it work?

**Comment by jaroszan** [comment]
Should Address be derived from OctetString, eg:

    type Address OctetString

?

And a case added for 0x08?

**Comment by fiorix** [comment]
Was looking at that. I'd rather change it to `[]byte` instead so we can easily accommodate IPv4, IPv6 and now E.164. I think it'd be less disruptive because we could still convert the byte slice to `net.IP` to begin with.

Also, I think we should add a `.Family() uint16` method to the Address type.

**Comment by fiorix** [comment]
Just looked at doing this in the code it doesn't seem too complex, although we'd have to think about the `.Serialize` method which today only accounts for IPv4 and IPv6 by trying to convert the underlying byte slice. In order to support other types we'll need a couple more types that can set the family address in the first 2 bytes.

For example, if you change `type Address net.IP` to `[]byte` everything still works just fine. But in order to set an address we'd need something like `addr := datatype.IPv4Address(x)` and that would return 0x01 + IP while `datatype.IPv6Address` would set family to 0x02 and `datatype.E164Address` to 0x08 without modifying the byte slice.

**Comment by jaroszan** [comment]
I have updated https://github.com/fiorix/go-diameter/blob/master/diam/datatype/address.go to behave in the same way as other types derived from OctetString and initial tests looks fine,

Having something like `datatype.IPv4Address(address)` would be nice. Or maybe something like `datatype.Address(type, value)`

**Comment by DefunctExodus** [comment]
woule be nice to see it supported , Just ran. Into the same issue

**Comment by fiorix** [comment]
Yeah I know, but that's a backwards incompatible change. I'm quite busy with other stuff so if you'd like to try a patch I'd be happy to review.

**Comment by jaroszan** [comment]
I have recently thought about how to resolve this issue and came up with the following concept:

1. Declare allowed address types in a dedicated data structure, eg.: `var allowedAddressTypes map[[2]byte]struct{}`

2. Modify `DecodeAddress` function to validate whether first two bytes are defined in the above 
structure, if not return an error. Else specific address types can be verified for correctness the same way it is done now for ipv4 and ipv6.

3. `Serialize` function verifies whether whether two first user submitted bytes for Address match `allowedAddressTypes`, if not - reject serialization. _User's duty is to prepare proper input_ (datatype + value).

4. Modify other functions to account for type change (from net.IP to []byte)

Since there are quite a few datatypes defined [here ](http://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml) it looks impractical (for me) to define dedicated type for each one.

Does this solution make sense?

**Comment by fiorix** [comment]
Makes sense to me, except for item 3, which break backwards compatibility.

**Comment by jaroszan** [comment]
Coming back to this one, do you think that adding new datatypes each having separate files is a reasonable way forward? (at least it does not look complex and easy to keep backwards compatibility - just leave address.go untouched). Or may be some new generic address type should be added which would accept two arguments - address type and value (leaving address.go untouched as well, however it looks less trivial than breeding address types). I have some local shortcuts to handle address types, however it would be easier to have proper functionality out of the box :)

**Comment by fiorix** [comment]
That's not bad

**Comment by jaroszan** [comment]
I've started analyzing ways to implement this and noticed that there is already datatype IPv4 in https://github.com/fiorix/go-diameter/blob/master/diam/datatype/ipv4.go , it looks it's not really used in the repo (apart from tests) and its serialization method does not take into account address type. Is it obsolete or is there some meaning to it?

**Comment by fiorix** [comment]
No, that IPv4 is from the NAS (network access server) dictionary.

**Comment by jaroszan** [comment]
NAS dictionary was added in October 2015, this file was added on February 2015 (rather moved (diam/avp/format/ipv4.go → diam/datatype/ipv4.go), initial version dates back to Jan 2014, I suspect it was there before). I could be missing something, but I can't find where it is used either.

**Comment by fiorix** [comment]
Yes the full dictionary came much later but I have always used IPv4 from the NAS dictionary because the system I used to test with required that AVP since the beginning.

**Comment by fiorix** [comment]
@jaroszan good to close this one?

**Comment by jaroszan** [comment]
Good to me :)
