### ISSUE TITLE
How to use multiple interfaces in one server

### ISSUE THREAD

**Issue by arixion** [fiorix/go-diameter#47]
I am using go-diameter and I need to create a basic server which supports multiple interfaces. How can I accomplish that ?

Thanks
Arpan

**Comment by fiorix** [comment]
Hi. For multiple diameter interfaces, you have to load all of your dictionaries XML using `dict.NewParser` or loading them on top of the default dictionary `dict.Default` by calling `Load`/`LoadFile`. For multiple network interfaces you have to call `ListenAndServe` on multiple combinations of [addr]:port.

Then, in your server, create the handlers for the diameter commands defined in your dictionary so the server knows how to handle such messages.
