### ISSUE TITLE
Question: SCTP support via native binding

### ISSUE THREAD

**Issue by Gladmir** [fiorix/go-diameter#48]
Hi,

Lack of SCTP support clearly discourages people to use GO based diameter backends at the moment.

 I know it's not nice to have c bindings but is there a chance that you would consider it, leveraging https://github.com/sctplab/usrsctp library?

**Comment by fiorix** [comment]
Yeah I'm aware of this limitation, it really sucks. I thought about the bindings but it's a lot of work and I don't have time or motivation to do it. All systems that I use to test and run this code in production uses TCP currently.

**Comment by Gladmir** [comment]
Alright, fair enough :)

I am trying to make the binding in a seperate repo at the moment, if it turns out to be idiomatic and simple, I'll get back to you.

cheers

**Comment by fiorix** [comment]
Once you get the bindings going, you can make up a layer implementing Go's `net` package (Dial, Listener, etc) so we don't need very specific changes in go-diameter's client and server code.

**Comment by Gladmir** [comment]
Yes, I was implying the net package's exposed interfaces by saying idiomatic and simple.

**Comment by artem-mindrov** [comment]
Seems I'm a little late but I currently have a build based on [this](https://github.com/ishidawataru/sctp). Tested this internally on RHEL7 with SCTP support and it seems to be working. Would you be interested in reviewing?

**Comment by fiorix** [comment]
Client support has recently landed with the `NewConn` where you can pass an existing `net.Conn` to create the client.

On the server side, someone has done most of the work already and I hope it'll be merged back here in the near future. I will update this once I know more.

**Comment by fiorix** [comment]
cc @emakeev

**Comment by fiorix** [comment]
SCTP support is in, from #78
