### ISSUE TITLE
Deadlock issue.

### ISSUE THREAD

**Issue by micrypt** [fiorix/go-diameter#49]
Kind sir, a design question… Using the following logic for a single diameter client which is intended for repeated re-use, there's an issue where the call to `c, err := cl.cli.Dial(cl.destinationAddress)` never returns after it gets executed. The aim of doing this is to reconnect in the case of a network interruption, as `cli.c` is used for writing CCR messages to a peer. Perhaps this is a case of misuse. Could you please clarify if it should be possible to call  `cli.Dial` multiple times? The definition of `cli` is further below.

```
func (cl *Client) connect() error {
    // Handle locking.
    utils.Logln(cl.debug, "connect(diameter://"+cl.DestinationHost()+"):", "dialling")
    c, err := cl.cli.Dial(cl.destinationAddress)
    if err == nil {
        utils.Logln(cl.debug, "connect(diameter://"+cl.DestinationHost()+"):", "acquiring lock")
        cl.mut.Lock()
        cl.c = c
        cl.mut.Unlock()
        utils.Logln(cl.debug, "connect(diameter://"+cl.DestinationHost()+"):", "released lock")
    }
    return err
}

func (cl *Client) Run() {
    // Make a persistent connection with back-off.
    backoff := time.Second
    for {
        utils.Logln(cl.debug, "connect(diameter://"+cl.DestinationHost()+"):", "attempting")
        err := cl.connect()
        if err != nil {
            utils.Logln(cl.debug, "connect(diameter-err://"+cl.DestinationHost()+"):", err)
            backoff *= 2
            if backoff > 20 {
                backoff = 20
            }
            time.Sleep(backoff)
            continue
        }
        utils.Logln(cl.debug, "connect(diameter-h):"+cl.DestinationHost()+"):", "handshake ok")
        backoff = 1
        // Wait until the server kicks us out or a write fails, requiring a
        // reconnect.
        select {
        case <-cl.c.(diam.CloseNotifier).CloseNotify():
            cl.mut.Lock()
            cl.c = nil
            cl.mut.Unlock()
            utils.Logln(cl.debug, "reconnect(diameter://"+cl.DestinationHost()+"):", "initiated")
        case <-cl.reconnect:
            cl.Close()
            utils.Logln(cl.debug, "reconnect(diameter://"+cl.DestinationHost()+"):", "initiated")
        }
        utils.Logln(cl.debug, "connect(diameter):"+cl.DestinationHost()+"):", "client disconnected - recreating connection")
    }
}
```

```
type Client struct {
    c                  diam.Conn
    cli                *sm.Client
    destinationAddress string
    destinationRealm   datatype.DiameterIdentity
    destinationHost    datatype.DiameterIdentity
    originRealm        datatype.DiameterIdentity
    originHost         datatype.DiameterIdentity
    productName        datatype.UTF8String
    reconnect          chan struct{}
    saveFunc           saveOperation
    Identifier         string
    db                 *sql.DB
    mut                *sync.RWMutex
    debug              bool
}
```

```
    smcli := &sm.Client{
        Dict:               dict.Default,
        Handler:            mux,
        MaxRetransmits:     3,
        RetransmitInterval: time.Second,
        EnableWatchdog:     true,
        WatchdogInterval:   5 * time.Second,
        AcctApplicationID: []*diam.AVP{diam.NewAVP(avp.AcctApplicationID, avp.Mbit, 0,
            AcctApplicationID),
        },
    }

    // Set message handlers.
    mux.HandleFunc("CCA", cl.ccaHandler)

    cl.cli = smcli
```

Thanks for your time & attention.

**Comment by fiorix** [comment]
Never returns? That's odd. Did you manage to track down the lock to a specific function?

**Comment by fiorix** [comment]
And yes, you can call Dial as many times you want. We do that in the example/client where it can make up N connections (configured from cmdline flags) for benchmarking purposes.

**Comment by micrypt** [comment]
Not yet. What appears to happen is that it gets stuck right after logging the results of the following call: `utils.Logln(cl.debug, "connect(diameter://"+cl.DestinationHost()+"):", "dialling")`. It would appear that calling `c, err := cl.cli.Dial(cl.destinationAddress)` a second time never returns a connection.

Unless I misunderstand, example/client creates a new connection for each client. What I was wondering was if it's possible to call `Dial` on a single `sm.Client` multiple times, or how best to approach dealing with a network interruption when one has previously called `cli.Dial` to get a connection. Running into cases such as this whilst trying to use a single client and the connection it returns from calling `Dial`:

```
2016/07/06 11:47:05 [charge(MSISDN, rec.digits): [error] 919555904037 55000 write tcp 10.12.36.76:51677->10.45.9.13:3868: use of closed network connection]
```

**Comment by micrypt** [comment]
So, it appears what was happening was that the second call to dial never failed. It appears to have been resolved by adding a timeout to the dial. 

For an idea of what changes I made for this, https://github.com/fiorix/go-diameter/pull/50. Perhaps one might consider a cleaner version of this?

**Comment by fiorix** [comment]
Hey @micrypt what's the status of this? I kinda lost track.

**Comment by micrypt** [comment]
It was resolved by a subsequently merged commit. Okay to close. Thanks.

2016年11月1日火曜日、Alexandre Fiori<notifications@github.com>さんは書きました:

**Comment by fiorix** [comment]
Thanks
