### ISSUE TITLE
include all of its supported applications

### ISSUE THREAD

**Issue by ibrohimislam** [fiorix/go-diameter#52]
on the RFC 6733 page 61, stated:
"The sender of the Capabilities-Exchange-Answer (CEA) SHOULD include all of its supported applications as a hint to the receiver regarding all of its application capabilities."

but in the implementation on `/go-diameter/diam/sm/cer.go`:

```
    if cer.AcctApplicationID != nil {
        for _, acct := range cer.AcctApplicationID {
            a.AddAVP(acct)
        }
    }
    if cer.AuthApplicationID != nil {
        for _, auth := range cer.AuthApplicationID {
            a.AddAVP(auth)
        }
    }
    if cer.VendorSpecificApplicationID != nil {
        for _, vs := range cer.VendorSpecificApplicationID {
            a.AddAVP(vs)
        }
    }
```

**Comment by fiorix** [comment]
What am I missing here? The code you pasted is doing what the text is saying.

**Comment by ibrohimislam** [comment]
in this context, CER receiver compose successCEA. But CEA only include CER's applications, not the CER receiver's supported applications.

**Comment by fiorix** [comment]
I see. We have two options to implement this: 1) to manually fill up the list of applications like we have in `sm.Client` or 2) pass the dictionary of the server to the state machine, which augments CEA with applications found in the dictionary.

**Comment by ibrohimislam** [comment]
How about create `sm.Server` that holds capabilities like `sm.Client`?

**Comment by fiorix** [comment]
Not bad, although we'd be duplicating stuff that is in the dictionary. We can have a method on `sm.Server` to automatically load things up from a `dict.Parser` object.

**Comment by jaroszan** [comment]
Should this one be closed with https://github.com/fiorix/go-diameter/commit/874e4c807bf1b36a0d556f43998f057f617d8cc2 ?

**Comment by fiorix** [comment]
Makes sense to me. If no objections I'll close it later today.
