### ISSUE TITLE
CER-CEA problems

### ISSUE THREAD

**Issue by ibrohimislam** [fiorix/go-diameter#53]
I don't know is RFC 6733 give some requirement about this. But in the real case, I'm facing that acct-application-id and auth-application-id share same id.

**Comment by fiorix** [comment]
What's the relation between this and go-diameter?

**Comment by jaroszan** [comment]
@ibrohimislam: Can you please provide details of your real case that go-diameter does not handle correctly?

**Comment by fiorix** [comment]
Abandoning this one unless @ibrohimislam has any more input. I'd be happy to reopen.
