### ISSUE TITLE
acct application 3 is not supported

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#54]
I am using client example as a starting point to connect to remote charging system (which is based on https://github.com/RestComm/jdiameter). CER which is sent from the client side includes auth-application-id = 4, remote peer returns auth-application-id = 4 and acct-application-id = 3.  Console logs `acct application 3 is not supported` and connection is not established.

It looks that go-diameter sm is not behaving correctly since both peers have application in common, but it looks that client expects to support all applications returned in CEA. As specified in RFC6733:

> The sender of the Capabilities-Exchange-Answer
> (CEA) SHOULD include all of its supported applications as a hint to
> the receiver regarding all of its application capabilities.

=== 
EDIT: It looks that there are 2 issues here:
1. Improper handling of CEA by the state machine
2. Application ID 3 should be part of diameter base

**Comment by jaroszan** [comment]
For point 1 (CEA handling):  It looks that behavior is caused by `validateAll` function in https://github.com/fiorix/go-diameter/blob/master/diam/sm/smparser/app.go. It should not return error if one of application ids is unsupported

**Comment by fiorix** [comment]
For the points you mentioned above, 1) we can change that `validateAll` to `validateAny` and for 2) it'd be a patch in the default dictionary in the `dict` pkg.

I cannot put work on this at the moment but would be happy to review any patches.

**Comment by jaroszan** [comment]
I will take a look at point 1 now, point 2 looks ok when using approach from https://github.com/fiorix/go-diameter/pull/55

**Comment by jaroszan** [comment]
Closed with https://github.com/fiorix/go-diameter/commit/874e4c807bf1b36a0d556f43998f057f617d8cc2
