### ISSUE TITLE
Requests that resulted in permanent errors should not be attempted again

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#57]
RFC6733, 7.1.5:

> Errors that fall within the permanent failures category are used to
> inform the peer that the request failed and should not be attempted
> again.

Currently go-diameter sm client attempts to reconnect even if permanent error code (eg. 5010) is received. Steps that take place are:
1. TCP connection is established
2. CE is performed, remote peer returns 5010
3. TCP connection is closed
4. If limit for retransmits is not exceeded go to step 1.

**Comment by jaroszan** [comment]
2 cases should be considered here:
1. CEA contains no app ids and 5010 code
2. CEA contains some app ids and 5010 code

**Comment by jaroszan** [comment]
This is a different issue than I initially thought and it is located in _**examples/client/client.go**_, client attempts to reconnect indefinitely regardless of type of error which happens in the progress.

```
for {
		c, err := connect()
		if err != nil {
			log.Println(err)
			backoff *= 2
			if backoff > 20 {
				backoff = 20
			}
			time.Sleep(time.Duration(backoff) * time.Second)
			continue
		}
		log.Println("Client connected, handshake ok")
		backoff = 1
		<-c.(diam.CloseNotifier).CloseNotify()
		log.Println("Client disconnected")
	}
```

One might guard oneself against such situations with something like this in case `err != nil`:

```
if err.Error()[len(err.Error())-4:] == "5010" {
                log.Println("Permenent error received, aborting connection attempts")
                break
}
```

But it does not look reliable (eg. err does not come necessarily from parsing CEA).

Such functionality (connect with backoff) can be potentially located somewhere inside sm/client.go and differentiate between type of errors and how to deal with them.

**Comment by fiorix** [comment]
That code in the example/client is an example, not something you'd use for real use cases.

One option is to implement the `diam.Conn` interface with specific client behavior, supporting things like auto reconnection (with back off), circuit breaker, and whatnot.

**Comment by jaroszan** [comment]
Closing since it is not really a bug
