### ISSUE TITLE
Builtin handling of requests with zero value Hop-By-Hop or End-to-End header fields

### ISSUE THREAD

**Issue by fuzzycow** [fiorix/go-diameter#65]
When using go-diameter examples, or sm handleCER:
Upon receiving a request with hop-by-hop or end-to-end id set to zero, go-diameter will respond with a message containing random hop-by-hop / end-to-end id. The client will then discard the answer.

To the best of my understanding: While RFC 3588 or 6733 encourage the use of unique Hop-by-Hop or End-to-End field values, they do not explicitly forbid zero values.  The RFCs do require that Diameter agent respond to a message with hop-by-hop and end-to-end ids equal to those received in the request.

The issue is with lack of distinction method argument zero values, and header zeros copied from request message header fields.
from NewMessage:
```
        if hopbyhop == 0 {
		hopbyhop = rand.Uint32()
	}
	if endtoend == 0 {
		endtoend = rand.Uint32()
	}
```

Example of an ugly fix for sm/cer.go successCER:
```
        a := m.Answer(diam.Success)
	a.Header.HopByHopID = m.Header.HopByHopID
	a.Header.EndToEndID = m.Header.EndToEndID
```

**Comment by fiorix** [comment]
Well, could make this change so long it doesn't break other things. I'm open for reviewing a PR.

**Comment by fiorix** [comment]
Hey @fuzzycow do you have any plans to work on this?

**Comment by fiorix** [comment]
Closing until this comes up again.
