### ISSUE TITLE
Hidden CCR errors

### ISSUE THREAD

**Issue by aholappa** [fiorix/go-diameter#67]
I'm trying to connect to a diameter server which accepts only valid origin-host values and only one connection per value. I'm getting this kind of error CEA:
```
Capabilities-Exchange-Answer (CEA)
{Code:257,Flags:0x20,Version:0x1,Length:192,ApplicationId:0,HopByHopId:0x8a0654a7,EndToEndId:0xe3c8490d}
	Result-Code {Code:268,Flags:0x40,Length:12,VendorId:0,Value:Unsigned32{5012}}
	Origin-Host {Code:264,Flags:0x40,Length:20,VendorId:0,Value:DiameterIdentity{*hidden*},Padding:0}
	Origin-Realm {Code:296,Flags:0x40,Length:28,VendorId:0,Value:DiameterIdentity{*hidden*},Padding:0}
	Host-IP-Address {Code:257,Flags:0x40,Length:16,VendorId:0,Value:Address{*hidden*},Padding:2}
	Vendor-Id {Code:266,Flags:0x40,Length:12,VendorId:0,Value:Unsigned32{16247}}
	Product-Name {Code:269,Flags:0x0,Length:32,VendorId:0,Value:UTF8String{Diameter Control Agent},Padding:2}
	Origin-State-Id {Code:278,Flags:0x40,Length:12,VendorId:0,Value:Unsigned32{1484188053}}
	Error-Message {Code:281,Flags:0x0,Length:40,VendorId:0,Value:UTF8String{Origin-Host already connected},Padding:3}
```
At the moment cea.go will try to parse this and since it doesn't contain _Auth-Application-ID_ I get error "ErrMissingApplication". I'd like to get access to the actual error for identifying different error cases. A simple way to do it in cea.go:

```
// Parse parses and validates the given message.
func (cea *CEA) Parse(m *diam.Message, localRole Role) (err error) {
...
...
	if _, err := app.Parse(m.Dictionary(), localRole); err != nil {
		if cea.ResultCode != diam.Success {
			return nil
		}
		return err
	}
...
```
with that I get an _ErrFailedResultCode_ with the correct code.
The check for _ResultCode_ could also be just after _Unmarshal_ is called, maybe in _sanityCheck_. I'm not sure which way would be the best.

**Comment by fiorix** [comment]
This hack works fine but I believe the right approach is to actually unmarshall error AVPs and return an error if they exist. Should be an easy patch and I'd be happy to review it.

**Comment by aholappa** [comment]
PR in #68
