### ISSUE TITLE
Multiple diameter payloads

### ISSUE THREAD

**Issue by DefunctExodus** [fiorix/go-diameter#72]
I am just wondering if there is any helpers do deal with multiple diameter payloads within a single TCP packet?

Currently i have some that contain up to 4 distinct diameter messages per payload

sorry if i have missed something obvious

**Comment by fiorix** [comment]
This shouldn't matter. The way we read packets off the wire does not look at the TCP level. Instead, we use the header length to read N bytes off the wire and consider that a single message. If there's more data on the same packet, our parser would find another header length and keep going.

In other words: this should work out of the box. If it doesn't, let me know, and we can re-open this.
