### ISSUE TITLE
build failure after sctp package changes

### ISSUE THREAD

**Issue by h8liu** [fiorix/go-diameter#82]
```
# github.com/fiorix/go-diameter/examples/diam_sctp_client
src/github.com/fiorix/go-diameter/examples/diam_sctp_client/main.go:91:41: sctpLAdds.IP undefined (type *sctp.SCTPAddr has no field or method IP)
```

Found by smallrepo.com:
https://smallrepo.com/builds/20180410-223930-028dc0d3

**Comment by h8liu** [comment]
I think the sctp changed the field to IPAddrs

https://github.com/ishidawataru/sctp/commit/cf586596b2065a714be2c97c4146e50daf645182

**Comment by fiorix** [comment]
Damn. cc @emakeev

**Comment by fiorix** [comment]
Gonna merge #83 and then #81 will need to be rebased.
