### ISSUE TITLE
Server example is not handling all commands

### ISSUE THREAD

**Issue by jaroszan** [fiorix/go-diameter#9]
When trying to send Credit Control message to server (go-diameter/examples/server/server.go) server generates error message:

Could not find preloaded Command with code 272

While error is self-explanatory it is not clear how it can be remedied. If server example is correct could you please provide an update to wiki how to properly extend server and client examples to handle CreditControl command?

**Comment by fiorix** [comment]
Check this out: http://godoc.org/github.com/fiorix/go-diameter/diam#ListenAndServe
By default, `ListenAndServe` uses the `dict.Default` if none/nil is specified. That means it is using this https://github.com/fiorix/go-diameter/blob/master/diam/dict/default.go dictionary, which is only the diameter base dictionary, not the credit control that you're looking for.

Credit control commands are defined in a separate dictionary, https://github.com/fiorix/go-diameter/blob/master/diam/dict/creditcontrol.go, which is not the default. You'd have to either 1) load the credit control dictionary on top of the default dictionary, or 2) use the credit control dictionary directly.

For example, before calling `ListenAndServe` (and the same applies to TLS), you could call `dict.Default.Load(bytes.NewReader(dict.CreditControlXML))` to load it on top of the default dict. With that, you'd have both the base dictionary (application id=0) and credit control (application id=4) and all their commands and AVPs available to you.

Next, you have to handle those commands and do your thing when you receive a CCR/CCA. For that, you have to create a handler and then map it with `diam.HandleFunc("CCR", myCCR)` and so on.

**Comment by jaroszan** [comment]
I have tried both ways:

1. Adding <code>dict.Default.Load(bytes.NewReader(dict.CreditControlXML))</code>

2. Modifying as suggested in client code:

<code>
parser, _ := dict.NewParser()
</code>
<code>
parser.Load(bytes.NewReader(dict.DefaultXML))
</code>
<code>
parser.Load(bytes.NewReader(dict.CreditControlXML))
</code>

And passing parser variable as the third parameter to <code>Dial</code> and <code>ServeAndListen</code> and  methods

I tried it with both client and server code. It resulted in unknown AVPs on the client side:

> Unknown {Code:415,Flags:0x40,Length:12,VendorId:0,Value:Unsigned32{103938196}} (Could not find AVP 415)

And in the same fashion on the server side with unrecognized code.

Can you please provide a complete working example of Credit-Control server or client for study?

P.S. there is a typo in client example (in the comments, load method is not capitalized on line 74)

**Comment by fiorix** [comment]
See the updated client and server code. They are obviously not fully implemented and need a bunch more work to comply with the spec.
