### ISSUE TITLE
Push notification support from server to client

### ISSUE THREAD

**Issue by krzychu135** [fiorix/go-diameter#94]
I can't find a way to send push message from server to client. 
Is it supported by go-diameter?

How can I send asynchronous message on event from server to client e.g.:
- Server-Initiated Credit Re-Authorization: https://tools.ietf.org/html/rfc4006#page-30
- Sy Spending-Status-Notification.

**Comment by fiorix** [comment]
It is possible and widely used. You have to get a hold of the diam.Conn from any message received by the server, and then you can arbitrarily send messages to the client using that diam.Conn.

**Comment by krzychu135** [comment]
Yes.
But if client will reconnect? diam.Conn will change and will point to closed socket. Right?
I would like to find current diam.Conn based on Origin-Host and Origin-Realm from Capabilities-Exchange request.
Is it possible?

**Comment by fiorix** [comment]
You can be notified when clients disconnect: https://godoc.org/github.com/fiorix/go-diameter/diam#CloseNotifier

If you use the diam/sm package for state machine, you can also get a notification from clients that pass the handshake: https://godoc.org/github.com/fiorix/go-diameter/diam/sm#HandshakeNotifier

Not sure what you mean by "current", but on the server side you can have multiple clients as peers and index them using AVPs from the CER in any way you want, and update the index based on the CloseNotifier mentioned above.
