### ISSUE TITLE
error on go get

### ISSUE THREAD

**Issue by 0rac1e** [fiorix/go-diameter#98]
go-diameter/diam/network_sctp.go:389:16: l.AcceptSCTP undefined (type sctpListener has no field or method AcceptSCTP)

**Comment by emakeev** [comment]
AcceptSCTP was added to github.com/ishidawataru/sctp prior to 70410bd:
    https://github.com/ishidawataru/sctp/blob/master/sctp_linux.go#L172
    https://github.com/ishidawataru/sctp/blob/master/sctp_unsupported.go#L45
Can you try 'go get -u ...' ?

**Comment by 0rac1e** [comment]
Tried clean `go get` after deleting src, got this error.
`go get -u ...` solved the problem. 
Thank you.
